C///////////////////////////////////////////////////////////////////////
C/
C/ Copyright (C) 2020 The Koko Project Developers
C/
C/ See the file COPYRIGHT.md in the top-level directory of this
C/ distribution
C/
C/ This file is part of Koko.
C/
C/ Koko is free software: you can redistribute it and/or modify it
C/ under the terms of the GNU General Public License as published by
C/ the Free Software Foundation, either version 3 of the License, or
C/ (at your option) any later version.
C/
C/ Koko is distributed in the hope that it will be useful, but
C/ WITHOUT ANY WARRANTY; without even the implied warranty of
C/ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
C/ GNU General Public License for more details.
C/
C/ You should have received a copy of the GNU General Public License
C/ along with Koko; see the file COPYING.  If not, see
C/ <https://www.gnu.org/licenses/>.
C/
C///////////////////////////////////////////////////////////////////////

      SUBROUTINE PIKFRESH(J)
!        USE WINTERACTER
          IMPLICIT NONE
          INTEGER J
          CHARACTER AJ*3
          INCLUDE 'resource.inc'
          INCLUDE 'datlen.inc'
          INCLUDE 'datmac.inc'
C       PIKUPS AND SOLVES
!     1  CALL WDialogSelect(IDD_PIKSLV)
          J=EDIT_SURFACE
          CALL ITOAA(J,AJ)
!     1  CALL WDialogPutInteger(IDF_SURFNUM,J)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCY,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCX,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_STY,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_STX,0)
!        IF(SOLVE(6,J).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_STY,1)
!                        END IF
!        IF(SOLVE(6,J).EQ.2.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_STY,1)
!                        END IF
!        IF(SOLVE(6,J).EQ.3.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_STY,1)
!                        END IF
!        IF(SOLVE(4,J).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_STX,1)
!                        END IF
!        IF(SOLVE(4,J).EQ.2.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_STX,1)
!                        END IF
!        IF(SOLVE(4,J).EQ.3.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_STX,1)
!                        END IF
!        IF(SOLVE(2,J).EQ.8.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCX,1)
!                        END IF
!        IF(SOLVE(2,J).EQ.9.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCX,1)
!                        END IF
!        IF(SOLVE(2,J).EQ.10.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCX,1)
!                        END IF
!        IF(SOLVE(2,J).EQ.11.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCX,1)
!                        END IF
!        IF(SOLVE(2,J).EQ.12.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCX,1)
!                        END IF
!        IF(SOLVE(2,J).EQ.13.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCX,1)
!                        END IF
!        IF(SOLVE(2,J).EQ.14.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCX,1)
!                        END IF
!        IF(SOLVE(8,J).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCY,1)
!                        END IF
!        IF(SOLVE(8,J).EQ.2.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCY,1)
!                        END IF
!        IF(SOLVE(8,J).EQ.3.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCY,1)
!                        END IF
!        IF(SOLVE(8,J).EQ.4.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCY,1)
!                        END IF
!        IF(SOLVE(8,J).EQ.5.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCY,1)
!                        END IF
!        IF(SOLVE(8,J).EQ.6.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCY,1)
!                        END IF
!        IF(SOLVE(8,J).EQ.7.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_SCY,1)
!                        END IF
!     1  CALL WDIALOGFIELDSTATE(IDF_SCY,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_SCX,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_STY,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_STX,2)
C
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P1,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P2,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P3,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P4,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P5,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P6,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P7,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P8,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P9,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P10,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P11,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P12,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P13,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P14,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P15,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P16,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P17,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P18,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P19,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P20,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P21,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P22,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P23,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P24,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P25,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P26,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P27,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P28,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P29,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P30,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P31,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P32,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P33,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P34,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P35,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P36,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P37,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P38,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P39,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P40,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P41,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P42,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P43,0)
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P44,0)
!        IF(PIKUP(1,J,1).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P1,1)
!                        END IF
!        IF(PIKUP(1,J,2).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P2,1)
!                        END IF
!        IF(PIKUP(1,J,3).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P3,1)
!                        END IF
!        IF(PIKUP(1,J,4).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P4,1)
!                        END IF
!        IF(PIKUP(1,J,5).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P5,1)
!                        END IF
!        IF(PIKUP(1,J,6).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P6,1)
!                        END IF
!        IF(PIKUP(1,J,7).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P7,1)
!                        END IF
!        IF(PIKUP(1,J,8).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P8,1)
!                        END IF
!        IF(PIKUP(1,J,9).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P9,1)
!                        END IF
!        IF(PIKUP(1,J,10).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P10,1)
!                        END IF
!        IF(PIKUP(1,J,11).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P11,1)
!                        END IF
!        IF(PIKUP(1,J,12).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P12,1)
!                        END IF
!        IF(PIKUP(1,J,13).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P13,1)
!                        END IF
!        IF(PIKUP(1,J,14).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P14,1)
!                        END IF
!        IF(PIKUP(1,J,15).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P15,1)
!                        END IF
!        IF(PIKUP(1,J,16).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P16,1)
!                        END IF
!        IF(PIKUP(1,J,17).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P17,1)
!                        END IF
!        IF(PIKUP(1,J,18).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P18,1)
!                        END IF
!        IF(PIKUP(1,J,19).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P19,1)
!                        END IF
!        IF(PIKUP(1,J,20).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P20,1)
!                        END IF
!        IF(PIKUP(1,J,21).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P21,1)
!                        END IF
!        IF(PIKUP(1,J,22).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P22,1)
!                        END IF
!        IF(PIKUP(1,J,23).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P23,1)
!                        END IF
!        IF(PIKUP(1,J,24).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P24,1)
!                        END IF
!        IF(PIKUP(1,J,25).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P25,1)
!                        END IF
!        IF(PIKUP(1,J,26).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P26,1)
!                        END IF
!        IF(PIKUP(1,J,27).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P27,1)
!                        END IF
!        IF(PIKUP(1,J,28).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P28,1)
!                        END IF
!        IF(PIKUP(1,J,29).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P29,1)
!                        END IF
!        IF(PIKUP(1,J,30).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P30,1)
!                        END IF
!        IF(PIKUP(1,J,31).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P31,1)
!                        END IF
!        IF(PIKUP(1,J,32).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P32,1)
!                        END IF
!        IF(PIKUP(1,J,33).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P33,1)
!                        END IF
!        IF(PIKUP(1,J,34).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P34,1)
!                        END IF
!        IF(PIKUP(1,J,35).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P35,1)
!                        END IF
!        IF(PIKUP(1,J,36).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P36,1)
!                        END IF
!        IF(PIKUP(1,J,37).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P37,1)
!                        END IF
!        IF(PIKUP(1,J,38).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P38,1)
!                        END IF
!        IF(PIKUP(1,J,39).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P39,1)
!                        END IF
!        IF(PIKUP(1,J,40).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P40,1)
!                        END IF
!        IF(PIKUP(1,J,41).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P41,1)
!                        END IF
!        IF(PIKUP(1,J,42).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P42,1)
!                        END IF
!        IF(PIKUP(1,J,43).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P43,1)
!                        END IF
!        IF(PIKUP(1,J,44).EQ.1.0D0) THEN
!     1  CALL WDIALOGPUTCHECKBOX(IDF_P44,1)
!                        END IF
!     1  CALL WDIALOGFIELDSTATE(IDF_P1,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P2,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P3,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P4,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P5,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P6,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P7,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P8,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P9,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P10,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P11,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P12,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P13,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P14,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P15,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P16,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P17,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P18,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P19,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P20,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P21,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P22,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P23,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P24,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P25,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P26,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P27,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P28,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P29,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P30,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P31,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P32,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P33,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P34,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P35,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P36,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P37,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P38,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P39,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P40,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P41,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P42,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P43,2)
!     1  CALL WDIALOGFIELDSTATE(IDF_P44,2)
!     1  CALL WDialogShow(-1,-1,0,Modeless)
          RETURN
      END
