# Form implementation generated from reading ui file 'QtGui/lidialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LIDialog(object):
    def setupUi(self, LIDialog):
        LIDialog.setObjectName("LIDialog")
        LIDialog.resize(400, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(LIDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=LIDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=LIDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LIDialog)
        self.buttonBox.accepted.connect(LIDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(LIDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LIDialog)

    def retranslateUi(self, LIDialog):
        _translate = QtCore.QCoreApplication.translate
        LIDialog.setWindowTitle(_translate("LIDialog", "Input Lens Identifier"))
