# Form implementation generated from reading ui file 'QtGui/newdialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewDialog(object):
    def setupUi(self, NewDialog):
        NewDialog.setObjectName("NewDialog")
        NewDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NewDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(parent=NewDialog)
        self.lineEdit.setGeometry(QtCore.QRect(132, 20, 241, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=NewDialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 71, 17))
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(parent=NewDialog)
        self.radioButton.setGeometry(QtCore.QRect(170, 70, 96, 23))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=NewDialog)
        self.radioButton_2.setGeometry(QtCore.QRect(280, 70, 96, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_2 = QtWidgets.QLabel(parent=NewDialog)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 54, 17))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=NewDialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 130, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=NewDialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 180, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(parent=NewDialog)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 171, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=NewDialog)
        self.label_4.setGeometry(QtCore.QRect(50, 190, 161, 17))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(NewDialog)
        self.buttonBox.accepted.connect(NewDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NewDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewDialog)

    def retranslateUi(self, NewDialog):
        _translate = QtCore.QCoreApplication.translate
        NewDialog.setWindowTitle(_translate("NewDialog", "Dialog"))
        self.label.setText(_translate("NewDialog", "Lens name"))
        self.radioButton.setText(_translate("NewDialog", "Millimeter"))
        self.radioButton_2.setText(_translate("NewDialog", "Inch"))
        self.label_2.setText(_translate("NewDialog", "Units"))
        self.label_3.setText(_translate("NewDialog", "Half angle of the field of view"))
        self.label_4.setText(_translate("NewDialog", "Entrance pupil radius"))
