#!/bin/bash
#
# generate build info string for KODS

printf "      character buildstr*80\n" > buildinfo.inc
printf "      buildstr = '[GCC %s]" `gcc -dumpfullversion` >> buildinfo.inc
printf "[build date: %s]" `date -Idate` >> buildinfo.inc
printf "[git commit: 0]'\n" >> buildinfo.inc

