#!/bin/bash
#
# generate build info string for KODS

printf "      character (len=80) :: buildstr\n" > buildinfo.inc
printf "      buildstr = '[GCC %s]" `gcc -dumpfullversion` >> buildinfo.inc
printf "[build date: %s]" `date -Idate` >> buildinfo.inc
printf "[git commit: %d]'\n" `git log --pretty=oneline|wc -l` >> buildinfo.inc

