C///////////////////////////////////////////////////////////////////////
C/
C/ Copyright (C) 2020 The Koko Project Developers
C/
C/ See the file COPYRIGHT.md in the top-level directory of this
C/ distribution
C/
C/ This file is part of Koko.
C/
C/ Koko is free software: you can redistribute it and/or modify it
C/ under the terms of the GNU General Public License as published by
C/ the Free Software Foundation, either version 3 of the License, or
C/ (at your option) any later version.
C/
C/ Koko is distributed in the hope that it will be useful, but
C/ WITHOUT ANY WARRANTY; without even the implied warranty of
C/ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
C/ GNU General Public License for more details.
C/
C/ You should have received a copy of the GNU General Public License
C/ along with Koko; see the file COPYING.  If not, see
C/ <https://www.gnu.org/licenses/>.
C/
C///////////////////////////////////////////////////////////////////////

!        CALL WDIALOGFIELDSTATE(IDF_MODNAME,2)
!        CALL WDIALOGCLEARFIELD(IDF_MODNAME)
!        CALL WDIALOGFIELDSTATE(IDF_ND,2)
!        CALL WDIALOGCLEARFIELD(IDF_ND)
!        CALL WDIALOGFIELDSTATE(IDF_VD,2)
!        CALL WDIALOGCLEARFIELD(IDF_VD)
!        CALL WDIALOGFIELDSTATE(IDF_DPART,2)
!        CALL WDIALOGCLEARFIELD(IDF_DPART)
!        CALL WDIALOGFIELDSTATE(IDF_FINDGLASS,2)
!        CALL WDIALOGCLEARFIELD(IDF_FINDGLASS)
!        CALL WDIALOGFIELDSTATE(IDF_MODTOCAT,2)
!        CALL WDIALOGFIELDSTATE(IDF_MODELOK,2)
